### ISSUE TITLE
gRPC with Vault - why does server initiates a CSR with client CN?

### ISSUE THREAD

**Issue by mmailhos** [johanbrandhorst/certify#107]
Hello and first of all thank you for the great project, it's definitely saving me a LOT of time when dealing with certificates with grpc! 

I have a general question regarding how the TLS handshake behaves with certify: why does the grpc Server is requesting a new certificate with client common name as Subject Alternative Name?

```
server1_1      | time="2020-02-08T23:59:56Z" level=error msg="Error getting server certificate" error="Error making API request.\n\nURL: PUT http://vault:8200/v1/pki/sign/admin\nCode: 400. Errors:\n\n* subject alternate name agent01.example.com not allowed by this role"
```

Of course, that can be easily fixed by changing my admin role and allowing that domain. But I am not sure to get why does the client CN is _getting propagated_ to the server CSR SAN?
Is it because of `tls.RequireAndVerifyClientCert` and a way of doing mutual authentication?

My piece of code, for the client and server:

```

	renewableToken := &certifyVault.RenewingToken{
		Initial:     key.VaultToken,
	}

	issuer := &certifyVault.Issuer{
		URL: &url.URL{
			Scheme: vaultURL.Scheme,
			Host:   vaultURL.Host,
		},
		Role:       "agent01",
		AuthMethod: renewableToken,
		TLSConfig: &tls.Config{RootCAs: client.CaCertPool, ServerName: "agent01.example.com"},
	}

	client.Certify = &certify.Certify{
		CommonName:  "agent01.example.com",
		Issuer:      issuer,
		Cache:       certify.NewMemCache(),
		Logger: logrusadapter.New(log.New()),
	}
```
```
	tlsConfig := &tls.Config{
		GetClientCertificate: client.Certify.GetClientCertificate,
		RootCAs: client.CaCertPool,
		ServerName: client.Host,
	}

	conn, err := grpc.Dial(serverAddr, grpc.WithTransportCredentials(credentials.NewTLS(tlsConfig)))
```

Ands server:

```
	renewableToken := &certifyVault.RenewingToken{
		Initial: s.VaultClient.Token(),
	}

	issuer := &certifyVault.Issuer{
		URL: &url.URL{
			Scheme: vaultURL.Scheme,
			Host:   vaultURL.Host,
		},
		TimeToLive: time.Hour,
		Role:  "admin",
		AuthMethod: renewableToken,
		TLSConfig: &tls.Config{RootCAs: s.CaCertPool, ServerName: "admin.example.com"},
	}

	s.Certify = &certify.Certify{
		CommonName: "admin.example.com",
		Issuer:      issuer,
		Cache:       certify.NewMemCache(),
		Logger: logrusadapter.New(log.New()),

```

```
	listener, _ := net.Listen("tcp", s.addr)

	tlsConfig := &tls.Config{
		GetCertificate: s.Certify.GetCertificate,
		RootCAs: s.CaCertPool,
		ServerName: "admin.example.com",
		ClientCAs: s.CaCertPool,
		ClientAuth:     tls.RequireAndVerifyClientCert,
	}

	gs := grpc.NewServer(grpc.Creds(credentials.NewTLS(tlsConfig)))
	gs.Serve(listener)
```

Thanks a lot!

**Comment by johanbrandhorst** [comment]
Hi Mathieu, thanks for your interest in the project!

That doesn't sound right at all, the server should be issuing a CSR with CN `admin.example.com`, according to your configuration. I noticed that you've configured the `ServerName` in your vault issuer `TLSConfig`, maybe this is what is causing the confusion? That field normally shouldn't be set, it should just use whatever the DNS is used for the Vault server.

Otherwise it looks fine, so if the problem persists, could you try to produce a minimal working example, or better yet, add a failing test to the tests?

Thanks!

**Comment by mmailhos** [comment]
Hi Johan, thank you very much for your reply. Indeed it was a DNS issue:
```
tlsConfig := &tls.Config{
		GetClientCertificate: client.Certify.GetClientCertificate,
		RootCAs: client.CaCertPool,
		ServerName: client.Host,
	}
```

My server name was wrong in the client, it should be the **Server**Name not Client. This is why the `tls.ClientHelloInfo.ServerName` was wrong on the server side as it was trying to issue the bad certificate. Just removing that parameter falls back to the actual resolved domain name.
 
If anyone else has the same issue, make sure all hosts are properly resolved too. In docker-compose it's pretty easy:

```
      networks:
        local:
          aliases:
            - vault.example.com
```

Thank you!
