### ISSUE TITLE
Undefined: acmpcaiface.ACMPCAAPI

### ISSUE THREAD

**Issue by robopuff** [johanbrandhorst/certify#111]
**Describe the bug**
in `github.com/johanbrandhorst/certify/issuers/aws/aws.go:33` with the newest `github.com/aws/aws-sdk-go-v2` compilator errors with 

```
# github.com/johanbrandhorst/certify/issuers/aws
../../../../johanbrandhorst/certify/issuers/aws/aws.go:33:9: undefined: acmpcaiface.ACMPCAAPI
```

**Steps to reproduce the bug**

```
$ go get -u github.com/aws/aws-sdk-go-v2
```

Try to compile with AWS CM issuer

**Expected behavior**

Compilator does not fail

**What happened instead**

Fatal compilation error

**Additional context**

**Comment by johanbrandhorst** [comment]
You need to use the same version as the go mod file dependency declares. I could try to update it, but this is not a bug.

**Comment by robopuff** [comment]
Yup, just checked it as well, since I am not using go mod it got me newest version by default :/

Not-a-bug 😅

**Comment by johanbrandhorst** [comment]
Unfortunately, I don't think I can update this version since it would mean a type change to my `Issuer` struct. Hopefully you can use the old version.
