### ISSUE TITLE
Support alt_names in Vault request

### ISSUE THREAD

**Issue by nvx** [johanbrandhorst/certify#114]
**Is your feature request related to a problem? Please describe.**
At the moment it is only possible to specify `uri_sans` and other_sans parameters to a Vault issuer. To use these features one must disable `use_csr_sans` in the Vault role, which means any DNS SANs in the CSR would be ignored.

**Describe the solution you'd like**
Add the ability for the Vault `alt_names` parameter to be configured as a part of the `vault.Issuer` struct similar to the existing `URISubjectAlternativeNames` and `OtherSubjectAlternativeNames` options. Note that the Vault alt_names parameter can be used for both DNS and Email names. For completeness it might be worth adding the `ip_sans` option at the same time which would fully round out the issuer to expose all underlying Vault options.

**Describe alternatives you've considered**
The obvious alternative is setting `use_csr_sans` to true in the Vault role and simply using the `CertConfig` to specify all SANs. The downside to this is this would require doing all access control in the PKI role (eg, one role per application) and being unable to use the otherwise powerful Vault policy configuration which allows specifying request arguments as a part of the Vault policy and can be more powerful.

Adding the options to the Vault issuer would still permit this option as existing behaviour would not change when those fields are not provided, but enables flexibility where required.

**Additional context**
https://www.vaultproject.io/api-docs/secret/pki/#sign-certificate

**Comment by johanbrandhorst** [comment]
Hi @nvx, thanks for the proposal! This sounds really good, and I think it should be fairly straightforward to add. Would you be interested in helping contribute this? I'd love to have someone else get their hands dirty to reduce the bus factor of this library. I would start here: https://github.com/johanbrandhorst/certify/blob/master/issuers/vault/vault.go#L22. You could even go ahead and TDD this by adding support to the tests first, maybe copy this and adjust: https://github.com/johanbrandhorst/certify/blob/master/issuers/vault/vault_test.go#L134-L170.

**Comment by nvx** [comment]
Indeed, you might remember me from PR #70. Just wanted to make sure there wasn't any issue with the concept before starting. :)

**Comment by nvx** [comment]
Should this be closed now that #115 is merged? Or do you want to wait until you cut a new release first?

**Comment by johanbrandhorst** [comment]
I thought it would be auto-closed :joy:
