### ISSUE TITLE
Missing vault issuer documentation

### ISSUE THREAD

**Issue by xaque208** [johanbrandhorst/certify#121]
Thank you for this project.  It looks quite interesting for my personal use case, and integration with golang and grpc.

I've been troubleshooting my install this week, and I'm unsure if this is a vault configuration issue, or something that the issuer is doing incorrectly.

```
subject alternate name server.example.com not allowed by this role"
```

Note that the following configuration does not have `server.example.com` as the CN.  Also note that I have verified that vault will indeed hand out certificates for the `.local` domain I'm showing below.

```
	cfg := certify.CertConfig{
		KeyGenerator: &myKeyGenerator{},
	}

	c := &certify.Certify{
		CommonName: "somethingelse.local",
		Issuer:     issuer,
		Cache:      certify.NewMemCache(),
		CertConfig: &cfg,
		RenewBefore: 24 * time.Hour,
		Logger:      logrusadapter.New(logger),
		IssueTimeout: 15 * time.Second,
	}
```

This leads me to want to know what the contents are of the CSR itself, so that I may confirm the behavior.  Is there a way?

In any case, some documentation as to how to get this all working in a real environment where an ACL is necessary would be super handy.  For example, I have the following policy:

```hcl
path "pki/issue/*" {
  capabilities = ["create", "update"]
}

path "pki/sign/*" {
  capabilities = ["create", "update"]
}

path "pki/certs" {
  capabilities = ["list"]
}

path "pki/revoke" {
  capabilities = ["create", "update"]
}

path "pki/tidy" {
  capabilities = ["create", "update"]
}

path "pki/cert/ca" {
  capabilities = ["read"]
}

path "auth/token/renew" {
  capabilities = ["update"]
}

path "auth/token/renew-self" {
  capabilities = ["update"]
}
```

But I'm unsure if that is too much permission to accomplish the issuing of a new cert.  I've kept log of everything I've done to get this far and can produce that if helpful.

In the above example, I'm unclear where the `server.example.com` SAN is being injected.  Note that I'm using certificate authentication, and the CN of the certificate I use to authenticate to vault is indeed the one mentioned in the error above, but from reading the code, the token metadata is not in use, unless I overlooked where that might be hiding.  If I understand the intent, the CN passed to certify is the only CN that should exist in the cert, and the above config has no SAN, so why is vault complaining?

Any thoughts or guidance here would be appreciated.

**Comment by bweston92** [comment]
Check your configuration for the create/update role with what you're trying to achieve. https://www.vaultproject.io/api-docs/secret/pki#create-update-role

**Comment by johanbrandhorst** [comment]
Hi Zach, thanks for your interest in the project! The talk linked in the README talks about everything required to set up Vault to authenticate the role used and restrict the CNs issued. It would be great to transcribe some of that into specific Vault documentation, but I don't really have a place for it right now.

To your issue, the specific error is probably because _something is trying to connect to your server via that address_, and it's causing Certify to attempt to issue a certificate for it. Certify will always try to create a certificate for the URL being used to reach it, and in this case it seems Vault is rightly rejecting that issuance.

**Comment by xaque208** [comment]
Thank you for the responses.  This makes sense.  In my reading of the code late last night, the part I didn't chase down was the hello objects, but I suppose that is the bit where the client asks for the server by name during the negotiation.  Is that right? Does that mean that the CN is only used on the client configuration to use as part of the CSR.  I'll straighten out my DNS here and try again.

**Comment by johanbrandhorst** [comment]
> Thank you for the responses. This makes sense. In my reading of the code late last night, the part I didn't chase down was the hello objects, but I suppose that is the bit where the client asks for the server by name during the negotiation. Is that right? Does that mean that the CN is only used on the client configuration to use as part of the CSR. I'll straighten out my DNS here and try again.

The CN is only _required_ for the client side, because then there is no other way to tell what name it should be using, but it is also used in server side requests, if configured. It will be added to SANS in the CSR: https://github.com/johanbrandhorst/certify/blob/master/certify.go#L145-L153.

It sounds like this resolved your issue, but would you like to contribute some documentation to make this more obvious to other users?

**Comment by xaque208** [comment]
Yeah, this is likely resolved as soon as I can stop arguing with my DNS servers.  Thanks for the information.  I don't mind submitting my setup steps once I get this all working.  Perhaps a repo wiki makes sense.  What do you think?

**Comment by johanbrandhorst** [comment]
A walkthrough of your setup on the wiki with a link from the README would be awesome.

**Comment by xaque208** [comment]
Can do, but it might take me a few days to play with it.  In the meantime, would you enable the wiki functionality for the project?

**Comment by johanbrandhorst** [comment]
> Can do, but it might take me a few days to play with it. In the meantime, would you enable the wiki functionality for the project?

Done!

**Comment by xaque208** [comment]
I see the wiki link, but for some reason it just redirects to the repo home.  I can give you a gist or something if that's easier if its permissions.  I've got my notes mostly in shape.

**Comment by johanbrandhorst** [comment]
Hey, I think we just needed an initial page, so I've added a few. Maybe you could add your setup here https://github.com/johanbrandhorst/certify/wiki/Setting-up-Vault-for-use-with-Certify?

**Comment by xaque208** [comment]
Strange,  I still don't see an edit.  I've not used wikis on GH.  But here are the notes, feel free to copy them.  I'm pretty sure I got the renewal right, but I've not confirmed manually yet.
https://gist.github.com/xaque208/1d106a7ce41b511e96d7c7c15bd1653a

**Comment by johanbrandhorst** [comment]
I updated https://github.com/johanbrandhorst/certify/wiki/Setting-up-Vault-for-use-with-Certify with your gist, thanks!

FYI, `authMethod.SetToken` is not supposed to be used like it is in your example, you're supposed to assign the `vault.Issuer.AuthMethod` to the `authMethod` :grimacing:. Sorry for the confusion, and I've documented it on the wiki page.

**Comment by xaque208** [comment]
Great, thank you for the advice, and this neat project.
