### ISSUE TITLE
go 1.15 x509 common name deprecation

### ISSUE THREAD

**Issue by xaque208** [johanbrandhorst/certify#122]
https://golang.org/doc/go1.15#commonname

I believe there will be updates necessary here to address this deprecation.

**Comment by johanbrandhorst** [comment]
I ran the tests against RC1 without any issues, do you have any particular problems?

**Comment by xaque208** [comment]
I wow, I did not leave very much information earlier.  Sorry about that.

The error I'm running into is this:
```
ERRO[2020-08-16T21:33:43-07:00] Get "https://vault.example.com8200/v1/auth/token/lookup-self": x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0
```

This appears to come from here: https://github.com/johanbrandhorst/certify/blob/master/issuers/vault/types.go#L67
But now after looking again, I see that the vault cert itself does not have a SAN.  I'll replace the certificate and see if I still have the issue.

The other thing that I was thinking needed an update was the `Certify` object that seems to require `CommonName`.  Omitting that portion yields an error, which I can get you if its useful.  I'm currently doing the following, but perhaps the `CommonName` is not effected by the deprecation?  Any pointers you have here would be appreciated.

https://github.com/xaque208/znet/blob/4ff74994197a37016af3eed3fd1cbe251be05ce8/znet/tls.go#L95

**Comment by johanbrandhorst** [comment]
`CommonName` in the `Certify` object is required because there's otherwise no way to know what SAN to use when requesting a client certificate. I'd set that explicitly rather than inferring it from some unrelated config. The server side always uses the name used to connect to _it_ when requesting a certificate from the issuer. Does that help? If you're only using it for server certificates I don't know if you need the Common Name.

**Comment by xaque208** [comment]
That does help, thank you.  I do wonder if perhaps the need to pass the SAN could be handled with a `NewCertify()` type pattern that I've used and seen.  I'm using client auth as well, and that struct literal I pointed at is used by both client and server, but perhaps I should split that out if its just the server side of the cert that has deprecated the CommonName.

**Comment by xaque208** [comment]
All good here, thank you for the pointers.
