### ISSUE TITLE
Possible nil panic in Vault issuer

### ISSUE THREAD

**Issue by beornf** [johanbrandhorst/certify#123]
**Describe the bug**
When reading the secret in the Vault issuer the line below may panic `invalid memory address or nil pointer dereference`:
https://github.com/johanbrandhorst/certify/blob/975cf0b3afb831bc31d5b037e3aefa670f9434d6/issuers/vault/vault.go#L160

This is due to a `nil` secret being received in the `signCSR` method:
https://github.com/johanbrandhorst/certify/blob/975cf0b3afb831bc31d5b037e3aefa670f9434d6/issuers/vault/vault.go#L205-L206

**Steps to reproduce the bug**
Vault server that is sealed or having temporary network issues during read/write.

**Expected behavior**
Return error in this edge case and not raise a panic to the application.

**Comment by johanbrandhorst** [comment]
Thanks for reporting this issue, could you verify whether the fix fixed it?

**Comment by beornf** [comment]
Yes that fixes the panic thanks. 👍
