### ISSUE TITLE
improper use of singleflight

### ISSUE THREAD

**Issue by nvx** [johanbrandhorst/certify#130]
singleflight is used to deduplicate requests to issue a new certificate

https://github.com/johanbrandhorst/certify/blob/168d95c011b19e999a92014956c0d537ab6ff2fc/certify.go#L140

Unfortunately the key used is a static string "issue" which if simultaneous requests come in for different common names that are not cached the wrong result may be returned.

Changing the key from the fixed string to the same key used for the cache (name in this context) would prevent the issue from occurring.

I haven't actually run into this issue myself (my usage of certify only ever has the one common name being issued) but stumbled across it while looking at the code for unrelated reasons so I thought I'd open a bug report rather than a trivial PR just in case I've misunderstood the logic being used.

**Comment by johanbrandhorst** [comment]
I think you're entirely right, good spot! I've opened https://github.com/johanbrandhorst/certify/pull/131 to fix it.

**Comment by nvx** [comment]
That looks like it'd do the trick!
