### ISSUE TITLE
Vault returns key type error

### ISSUE THREAD

**Issue by poolski** [johanbrandhorst/certify#209]
**Describe the bug**

When trying to issue a certificate for a basic HTTPS web server, Certify connects to Vault fine, but when calling the `/v1/pki/sign/rolename` endpoint, Vault returns an error: 
```
Error making API request.

URL: PUT https://localhost:8200/v1/pki/sign/example.com
Code: 400. Errors:

* role requires keys of type rsa
```

**Steps to reproduce the bug**

Request a certificate from Vault via the `certify.GetCertificate` hook in `http.Server`'s `TLSConfig`. 

**Expected behavior**

A certificate is returned and the request proceeds

**Extra comments**

This is admittedly a Vault API error, when running against Vault 1.11.0, but it seems weird that regardless of which key type is set in the Vault role, Certify's request is denied. Is this to do with Vault API changes?

**Comment by johanbrandhorst** [comment]
Hi, thanks for your issue. I upgraded the version of Vault tested to v1.11.0 and cannot reproduce the error in our tests. Are you sure this isn't a misconfiguration in your set up? Maybe the role is restricted to RSA keys?

**Comment by poolski** [comment]
Hi @johanbrandhorst, thanks for your response! 😄 

It's possible, but following the [guide](https://learn.hashicorp.com/tutorials/vault/pki-engine), I don't see anything outrageous being suggested there. It seems like they _do_ require you to configure the role with a specific keytype. That said, I've tried experimenting with configuring the role with each available keytype inside Vault and Certify throws the same error, regardless of what the keytype is set to.

That makes me think that Certify is expecting to use a role which has the `any` keytype set, rather than a specific one?

I couldn't find which keytype Certify tries to use by digging through the code, but it might be hidden somewhere I haven't looked...

**Comment by poolski** [comment]
Ah. According to the [tests](https://github.com/johanbrandhorst/certify/blob/40a7aca60055de2a5d86cad6d020d52867183cda/issuers/vault/vault_suite_test.go#L191) you're expecting a `keytype` of `any`, rather than a specific one. Could this be what's causing the error?

**Comment by johanbrandhorst** [comment]
Hi, thanks for your reply. I suppose that could be the issue. I'm not sure I understand, is there something certify can do to let the user specify the key type? It would seem preferable to me for certify to be as lax as possible. If there are docs updates to be made, I would be very happy to review a contribution from you 😄.

**Comment by poolski** [comment]
Heya, sorry for the delay. I've been off sick with The Plague. 

I think I've worked out what's going on here....
https://github.com/hashicorp/vault/blob/main/builtin/logical/pki/cert_util.go#L750-L831

Vault checks what the CSR's keytype is, and falls into different code paths depending on what that is, but by default, Certify is sending an `ecdsa` key when it generates the private key for the CSR here: https://github.com/johanbrandhorst/certify/blob/master/internal/csr/csr.go#L16-L19

To make this error go away, you would need to pass a different `KeyGenerator` to `csr.FromCertConfig()` which uses the RSA algorithm. I'm not familiar with the testing framework you're using and I'm struggling to work out whether you're testing for a situation where the Vault role is created with a keytype that isn't `any`. 

When I change the `key_type` to `rsa` in the Vault [test suite](https://github.com/johanbrandhorst/certify/blob/40a7aca60055de2a5d86cad6d020d52867183cda/issuers/vault/vault_suite_test.go#L187-L202), all tests immediately fail because Certify is passing an ECDSA key along, which is what's causing the issue I reported.

**Comment by poolski** [comment]
From tinkering further, I think the sensible approach would be to document the process for using a Vault PKI role that uses a non-EC key type, making it clear that it's necessary to write a custom `KeyGenerator` which satisfies the `certify.KeyGenerator` interface. I'll submit a PR to the `README` unless there's a better place to document it?
