### ISSUE TITLE
Allow a logger to be configured

### ISSUE THREAD

**Issue by johanbrandhorst** [johanbrandhorst/certify#36]
Probably just in the Certify struct for now, since any errors seen in the issuers should be propagate to Certify. The interface must default to a `noop` implementation that can safely be called. Perhaps just use `logrus` as well.

**Comment by sagikazarmark** [comment]
I've created an interface and a set of (opinionated) best practices around logging in libraries and applications. It might help (or not), but leaving it here anyway: https://github.com/goph/logur 🙂

**Comment by johanbrandhorst** [comment]
Thanks for sharing!
