### ISSUE TITLE
Implement an issuer for whatever Istio uses under the hood to issue certs

### ISSUE THREAD

**Issue by johanbrandhorst** [johanbrandhorst/certify#39]
Had a quick look but couldn't find what Istio uses under the hood, but there are certs being issued so there should be an issuer somewhere!

**Comment by sagikazarmark** [comment]
Certificate management is done by the Citadel component, but I'm not sure if it exposes an API or if it's even useful to issue certificates using it. Envoy sidecar proxies handle TLS communication within the mesh between services, applications usually aren't involved in the process.

**Comment by johanbrandhorst** [comment]
Thanks for that, I'll probably just close this issue then :).
