### ISSUE TITLE
Using dep with certify adds a lot of additional dependencies

### ISSUE THREAD

**Issue by espang** [johanbrandhorst/certify#48]
I am using certify in a sub-project and use dep to manage my dependencies.

**Steps to reproduce the bug**

I am running `dep ensure -update {sub-project}`

**Expected behavior**

My vendor folder contains certify and the updated sub-project.

**What happened instead**

The vendor folder contains in addition to the expected files:
* protoc-gen-go
* gingko
* moq

**Comment by johanbrandhorst** [comment]
I've opened https://github.com/golang/dep/issues/2112 to discuss the best way to solve this from the point of view of `dep` and `go modules` interaction. However, I think we should be able to solve this in this repo by moving it into a separate package, so I will try to do that.

**Comment by espang** [comment]
Thank you for the quick fix. The changes work for me
