### ISSUE TITLE
Ability to reuse private key

### ISSUE THREAD

**Issue by wioxjk** [johanbrandhorst/certify#99]
**Is your feature request related to a problem? Please describe.**
In order to ease up DANE/TLSA implementations it would be nice to be able to keep the private key.

**Describe the solution you'd like**
Possibility to keep the private key and reuse it

**Describe alternatives you've considered**
 Automate the process of creating a hash of the certificate, and the publish it to a supported DNS-provider

**Comment by johanbrandhorst** [comment]
Hi @wioxjk, did you raise this issue on the wrong project? Looks like you raised [an issue](https://github.com/webprofusion/certify/issues/458) with `webprofusion/certify` too.

**Comment by johanbrandhorst** [comment]
However unintentional this was, you made me think, and I think this would still be useful for this project :joy:. It should already be possible by specifying a custom `CertConfig.KeyGenerator` that returns the same key every time, and I think we could make that the default behaviour.

**Comment by wioxjk** [comment]
Yes! I did raise the issue on the wrong project, and when I realized my misstake (same second as I pressed comment), I thought this would be a good thing for this too! 😅

I am glad that I could provide useful feedback, and hopefully a laugh :)

**Comment by webprofusion-chrisc** [comment]
@johanbrandhorst very random off-topic party-pooper comment: certify is a registered trademark of another piece of software (http://tmsearch.uspto.gov/bin/showfield?f=doc&state=4801:gno42y.2.49), that's why we changed our app from 'Certify' to 'Certify The Web'. Might want to rename before it becomes a problem.

**Comment by johanbrandhorst** [comment]
Thanks Chris, that is good to know. I'll take my chances for now as I've no commercial benefit from this, and it's also quite a small project.

**Comment by bweston92** [comment]
@webprofusion-chrisc only trademarked in the US and as I believe Johan is in the UK and it is in a different "Goods and services" category, I can't see a jewellers care about a software library.

**Comment by webprofusion-chrisc** [comment]
@johanbrandhorst yep no worries, I just didn't want to risk it with my project, commercial or not. @bweston92 the name is used in multiple categories and the one I was concerned about is a software one.
